const userTypes = {
  SET_CURRENT_USER_OUT: 'SET_CURRENT_USER_OUT',
  // SIGN
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  SET_USER: 'SET_USER',
  SET_DOCTOR: 'SET_DOCTOR',
  SET_USERNAME: 'SET_USERNAME',
  SET_PROFILE_DATA: 'SET_PROFILE_DATA',
  // TOKEN
  SET_TOKEN: 'SET_TOKEN',
  RESET_TOKEN: 'RESET_TOKEN',
  // RESET FORM
  RESET_AUTH_FORMS: 'RESET_AUTH_FORMS',
  RESET_ERRORSSTATE_FORMS: 'RESET_ERRORSSTATE_FORMS',
  RESET_STATES: 'RESET_STATES',
  // ERROR
  SET_ERRORS: 'SET_ERRORS',
};

export default userTypes;
