# Generated by Django 3.2.12 on 2022-03-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientIntakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('birth', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('patient_medical_hostory', models.CharField(max_length=50, null=True)),
                ('current_medications', models.CharField(max_length=50, null=True)),
                ('list_allergies', models.CharField(max_length=200, null=True)),
                ('healthy_unhealthy', models.CharField(max_length=1250)),
                ('father', models.CharField(max_length=30, null=True)),
                ('mother', models.CharField(max_length=30, null=True)),
                ('brother', models.CharField(max_length=50, null=True)),
                ('sister', models.CharField(max_length=50, null=True)),
                ('reason_for_consultation', models.CharField(max_length=100)),
                ('question1', models.CharField(max_length=100)),
                ('question2', models.CharField(max_length=100)),
                ('question3', models.CharField(max_length=100)),
                ('appointment', models.CharField(max_length=64, null=True)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
    ]
