# Generated by Django 3.1.3 on 2022-01-20 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.CharField(blank=True, max_length=1250)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('specialization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.specialization')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('info', models.TextField(blank=True, max_length=1250, verbose_name='Information')),
                ('address', models.CharField(blank=True, max_length=15, null=True)),
                ('street', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True)),
                ('npi_number', models.CharField(max_length=10, null=True)),
                ('state_license_number', models.CharField(max_length=12, null=True)),
                ('profile_Pic', models.ImageField(blank=True, upload_to=None, verbose_name='Profile Picture')),
                ('award_Pic', models.ImageField(blank=True, upload_to=None, verbose_name='Award_ Picture')),
                ('consultation_fees', models.CharField(blank=True, max_length=10, verbose_name='Consultation Fees')),
                ('available_days', models.CharField(choices=[('monday', 'Mon'), ('tuesday', 'Tues'), ('wednesday', 'Wed'), ('thursday', 'Thurs'), ('friday', 'Fri'), ('saturday', 'Sat'), ('sunday', 'Sun')], default='Mon', max_length=10)),
                ('time_slots', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('traige_score', models.CharField(blank=True, max_length=10)),
                ('diagnosis_ref', models.CharField(blank=True, max_length=12)),
                ('profile_Pic', models.ImageField(blank=True, upload_to=None, verbose_name='Profile Picture')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('date', models.DateField(verbose_name='Date')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.customer')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.doctor')),
            ],
        ),
    ]
