# Generated by Django 3.1.3 on 2022-01-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_doctor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_time',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
