# Generated by Django 3.1.3 on 2022-02-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customer_phone_number'),
        ('authentication', '0004_doctor_consultation_time'),
    ]

    operations = [
    ]
