# Generated by Django 3.1.3 on 2022-02-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_merge_20220203_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_Pic',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='award_Pic',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='profile_Pic',
        ),
        migrations.AddField(
            model_name='customer',
            name='avatar_pic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.CharField(max_length=1250, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
