# Generated by Django 3.1.3 on 2022-01-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientintakemodel',
            name='img1',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='patientintakemodel',
            name='img2',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
