# Generated by Django 3.1.3 on 2022-01-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20220127_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientintakemodel',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='patientintakemodel',
            name='img2',
        ),
    ]
