# Generated by Django 3.1.3 on 2022-01-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20220127_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientintakemodel',
            name='customer',
        ),
    ]
