# Generated by Django 3.1.3 on 2022-02-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patientintakemodel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientintakemodel',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='patientintakemodel',
            name='caffiene',
        ),
        migrations.RemoveField(
            model_name='patientintakemodel',
            name='currently_feeling_didnt_live',
        ),
        migrations.RemoveField(
            model_name='patientintakemodel',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='patientintakemodel',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='patientintakemodel',
            name='had_feeling_didnt_want_to_live',
        ),
        migrations.RemoveField(
            model_name='patientintakemodel',
            name='health_unhealth',
        ),
        migrations.RemoveField(
            model_name='patientintakemodel',
            name='mental_health_symptoms',
        ),
        migrations.RemoveField(
            model_name='patientintakemodel',
            name='smoke',
        ),
        migrations.AddField(
            model_name='patientintakemodel',
            name='current_medications',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientintakemodel',
            name='healthy_unhealthy',
            field=models.CharField(max_length=1250, null=True),
        ),
    ]
