# Generated by Django 3.1.3 on 2022-02-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20220207_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientintakemodel',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patientintakemodel',
            name='weight',
        ),
        migrations.AlterField(
            model_name='patientintakemodel',
            name='reason_for_consultation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
