# Generated by Django 3.1.3 on 2022-02-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20220207_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientintakemodel',
            name='birth',
        ),
    ]
